### ISSUE TITLE
Close this repo

### ISSUE THREAD

**Issue by GeorgLink** [Bitergia/cauldron.io#16]
I believe this repo is for an old version of Cauldron.io 

We are now found on GitLab: https://gitlab.com/cauldronio

This issue is to suggest closing this repo or depreciating it or something to make it clear this is no longer current.

**Comment by connorlindsey** [comment]
This would be very helpful (or maybe point to the Gitlab repo). In general, I had a hard time finding documentation on Cauldron. Seems like it is scattered. 

It would've been very nice to have a link to the documentation on the cauldron.io website.

**Comment by jgbarah** [comment]
Thanks a lot for the heads-up, @connorlindsey. Sorry for ignoring this issue for so long, @GeorgLink. I've changed the README of the repo, adding some data about the current cauldron.io, and I'm about to change its description, and make it R/O.
