### ISSUE TITLE
repository missing

### ISSUE THREAD

**Issue by davidak** [Bitergia/cauldron.io#6]
https://dashboard.cauldron.io/goto/640ce39a39618a46a8650429788f81f7

the most active and most interesting repository "nixpkgs" is not analyzed.

does it need longer or is not included because it is too big?

**Comment by acs** [comment]
Cauldron collects the 30 repositories most recently updated. So in this case, it should have analyzed all the repositories for Nix/Nixpkgs/NixOS (there are 30). So probably there is some issue in the data collection with this organization. Maybe you can try to refresh the dashboard and see if that fixes the problem.

**Comment by davidak** [comment]
I refreshed the dashboard and nixpkgs is now included.

http://cauldron.io/dashboards/nixos

**Comment by acs** [comment]
Great @davidak !
