### ISSUE TITLE
Please remove 'hydra' dashboard

### ISSUE THREAD

**Issue by Anton-Latukha** [Bitergia/cauldron.io#7]
I was interested in NixOS/Hydra.

And created dashboard.
"Project (organization or user) name?"
Does not mean that it going to pull from GitHub on that `<organization>/<project>`
So for name I supplied `hydra`.

And not I can not find how to delete that dashboard.

**Comment by jsmanrique** [comment]
By project `organization` or `user name`, it means the `<organization>` part. You should ask for `NixOS` to get the latest 30 active repositories, that would include `hydra`.

Dashboards can not be removed by hand.  They are removed if they are not updated during 30 days AFAIK.

Sorry for the inconvenience. 

Could you check if you can get `NixOS` dashboard?

**Comment by jgbarah** [comment]
I saw NixOS was already analyzed. I've asked for a refresh of it, should be ready soon. Once it is ready, please check:

http://cauldron.io/dashboards/nixos

You can filter nixos/hydra in it by clicking, in the repositories table, on the cell with the name of the repo (be careful not clicking on the name itself, which is a link, and would load the repo instead of filtering the dashboard for the activity in it).

**Comment by Anton-Latukha** [comment]
@jsmanrique 
@jgbarah 

Yes. thank you.

I would ask or to make the description to that main fiend more informative.
I am not a dumb person. And seen some configurations as DevOps.

To try-out what user wants, because person has a single shot.
And that would also build a legitimate demos of repositories.
Because people tried some stuff that is not on GitHub, and that is in the list now. 

So if you want this to be a great demo ground, please make commentary on this field more descriptive.

**Comment by Anton-Latukha** [comment]
Also.

After that, I thought that NixOS org already added. And Hydra is inside it.
So I can conf ELK dashboard to select only Hydra. 

For a couple of days several times I triggered updates on NixOS info.

And it does not go beyond 2017-09-18.

I think this is because NixOS community right there hit an abnormal 2-3x activity, because of NixOS 17.09 release deadline.

**Comment by Anton-Latukha** [comment]
Ok.
Now it is updated.

But it does not show real stat.
Probably `nixos/nixpkgs` is not processed. This is the repo that has abnormal activity.

**Comment by jgbarah** [comment]
Hi, @Anton-Latukha. Thanks a lot for your comments.

Why do you think it is not showing real stats?

nixos/nixpkgs is included in the dashboard, you can see it in the list of repos (middle right, in the main panel in the dashboard). Or click the link  below to check *only* activity for that repo:

https://dashboard.cauldron.io/goto/329d83a0acb8012fb752e34f52cf6a9c

**Comment by Anton-Latukha** [comment]
It indeed shows now 👍

As I said, I was updating it myself, and it was not progressing.

But today I saw that first it showed stats without `nixpkgs` - the biggest repo.
And then it also includded `nixpkgs`.

Cool 👍

**Comment by jgbarah** [comment]
Great! Can we consider this issue closed, then?

**Comment by Anton-Latukha** [comment]
Yes
